<?php declare(strict_types=1);

namespace Osumi\OsumiFramework\Routes;

use Osumi\OsumiFramework\Routing\ORoute;
use Osumi\OsumiFramework\App\Module\Admin\AdminLogin\AdminLoginComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteAsset\DeleteAssetComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteBackground\DeleteBackgroundComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteBackgroundCategory\DeleteBackgroundCategoryComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteCharacter\DeleteCharacterComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteConnection\DeleteConnectionComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteItem\DeleteItemComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteScenario\DeleteScenarioComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteScenarioObject\DeleteScenarioObjectComponent;
use Osumi\OsumiFramework\App\Module\Admin\DeleteWorld\DeleteWorldComponent;
use Osumi\OsumiFramework\App\Module\Admin\GenerateMap\GenerateMapComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetAssetList\GetAssetListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetBackgroundCategoryList\GetBackgroundCategoryListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetBackgroundList\GetBackgroundListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetCharacterList\GetCharacterListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetItemList\GetItemListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetScenario\GetScenarioComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetScenarioList\GetScenarioListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetScenarioObjectList\GetScenarioObjectListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetTagList\GetTagListComponent;
use Osumi\OsumiFramework\App\Module\Admin\GetWorldList\GetWorldListComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveAsset\SaveAssetComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveBackground\SaveBackgroundComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveBackgroundCategory\SaveBackgroundCategoryComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveCharacter\SaveCharacterComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveConnection\SaveConnectionComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveItem\SaveItemComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveScenario\SaveScenarioComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveScenarioData\SaveScenarioDataComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveScenarioObject\SaveScenarioObjectComponent;
use Osumi\OsumiFramework\App\Module\Admin\SaveWorld\SaveWorldComponent;
use Osumi\OsumiFramework\App\Module\Admin\SelectWorldStart\SelectWorldStartComponent;
use Osumi\OsumiFramework\App\Filter\AdminFilter;

ORoute::prefix('/admin', function() {
  ORoute::post('/login',                      AdminLoginComponent::class);
  ORoute::post('/delete-asset',               DeleteAssetComponent::class,               [AdminFilter::class]);
  ORoute::post('/delete-background',          DeleteBackgroundComponent::class,          [AdminFilter::class]);
  ORoute::post('/delete-background-category', DeleteBackgroundCategoryComponent::class,  [AdminFilter::class]);
  ORoute::post('/delete-character',           DeleteCharacterComponent::class,           [AdminFilter::class]);
  ORoute::post('/delete-connection',          DeleteConnectionComponent::class,          [AdminFilter::class]);
  ORoute::post('/delete-item',                DeleteItemComponent::class,                [AdminFilter::class]);
  ORoute::post('/delete-scenario',            DeleteScenarioComponent::class,            [AdminFilter::class]);
  ORoute::post('/delete-scenario-object',     DeleteScenarioObjectComponent::class,      [AdminFilter::class]);
  ORoute::post('/delete-world',               DeleteWorldComponent::class,               [AdminFilter::class]);
  ORoute::post('/generate-map',               GenerateMapComponent::class,               [AdminFilter::class]);
  ORoute::post('/asset-list',                 GetAssetListComponent::class,              [AdminFilter::class]);
  ORoute::post('/background-category-list',   GetBackgroundCategoryListComponent::class, [AdminFilter::class]);
  ORoute::post('/background-list',            GetBackgroundListComponent::class,         [AdminFilter::class]);
  ORoute::post('/character-list',             GetCharacterListComponent::class,          [AdminFilter::class]);
  ORoute::post('/item-list',                  GetItemListComponent::class,               [AdminFilter::class]);
  ORoute::post('/get-scenario',               GetScenarioComponent::class,               [AdminFilter::class]);
  ORoute::post('/scenario-list',              GetScenarioListComponent::class,           [AdminFilter::class]);
  ORoute::post('/scenario-object-list',       GetScenarioObjectListComponent::class,     [AdminFilter::class]);
  ORoute::post('/tag-list',                   GetTagListComponent::class,                [AdminFilter::class]);
  ORoute::post('/world-list',                 GetWorldListComponent::class,              [AdminFilter::class]);
  ORoute::post('/save-asset',                 SaveAssetComponent::class,                 [AdminFilter::class]);
  ORoute::post('/save-background',            SaveBackgroundComponent::class,            [AdminFilter::class]);
  ORoute::post('/save-background-category',   SaveBackgroundCategoryComponent::class,    [AdminFilter::class]);
  ORoute::post('/save-character',             SaveCharacterComponent::class,             [AdminFilter::class]);
  ORoute::post('/save-connection',            SaveConnectionComponent::class,            [AdminFilter::class]);
  ORoute::post('/save-item',                  SaveItemComponent::class,                  [AdminFilter::class]);
  ORoute::post('/save-scenario',              SaveScenarioComponent::class,              [AdminFilter::class]);
  ORoute::post('/save-scenario-data',         SaveScenarioDataComponent::class,          [AdminFilter::class]);
  ORoute::post('/save-scenario-object',       SaveScenarioObjectComponent::class,        [AdminFilter::class]);
  ORoute::post('/save-world',                 SaveWorldComponent::class,                 [AdminFilter::class]);
  ORoute::post('/select-world-start',         SelectWorldStartComponent::class,          [AdminFilter::class]);
});
