<?php declare(strict_types=1);

namespace Osumi\OsumiFramework\Routes;

use Osumi\OsumiFramework\Routing\ORoute;
use Osumi\OsumiFramework\App\Module\Admin\AdminLogin\AdminLoginAction;
use Osumi\OsumiFramework\App\Module\Admin\AssetList\AssetListAction;
use Osumi\OsumiFramework\App\Module\Admin\BackgroundCategoryList\BackgroundCategoryListAction;
use Osumi\OsumiFramework\App\Module\Admin\BackgroundList\BackgroundListAction;
use Osumi\OsumiFramework\App\Module\Admin\CharacterList\CharacterListAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteAsset\DeleteAssetAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteBackground\DeleteBackgroundAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteBackgroundCategory\DeleteBackgroundCategoryAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteCharacter\DeleteCharacterAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteConnection\DeleteConnectionAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteItem\DeleteItemAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteScenario\DeleteScenarioAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteScenarioObject\DeleteScenarioObjectAction;
use Osumi\OsumiFramework\App\Module\Admin\DeleteWorld\DeleteWorldAction;
use Osumi\OsumiFramework\App\Module\Admin\GenerateMap\GenerateMapAction;
use Osumi\OsumiFramework\App\Module\Admin\GetScenario\GetScenarioAction;
use Osumi\OsumiFramework\App\Module\Admin\ItemList\ItemListAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveAsset\SaveAssetAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveBackground\SaveBackgroundAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveBackgroundCategory\SaveBackgroundCategoryAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveCharacter\SaveCharacterAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveConnection\SaveConnectionAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveItem\SaveItemAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveScenario\SaveScenarioAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveScenarioData\SaveScenarioDataAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveScenarioObject\SaveScenarioObjectAction;
use Osumi\OsumiFramework\App\Module\Admin\SaveWorld\SaveWorldAction;
use Osumi\OsumiFramework\App\Module\Admin\ScenarioList\ScenarioListAction;
use Osumi\OsumiFramework\App\Module\Admin\ScenarioObjectList\ScenarioObjectListAction;
use Osumi\OsumiFramework\App\Module\Admin\SelectWorldStart\SelectWorldStartAction;
use Osumi\OsumiFramework\App\Module\Admin\TagList\TagListAction;
use Osumi\OsumiFramework\App\Module\Admin\WorldList\WorldListAction;
use Osumi\OsumiFramework\App\Filter\AdminFilter;

ORoute::group('/admin', 'json', function() {
  ORoute::post('/login',                      AdminLoginAction::class);
  ORoute::post('/asset-list',                 AssetListAction::class,                [AdminFilter::class]);
  ORoute::post('/background-category-list',   BackgroundCategoryListAction::class,   [AdminFilter::class]);
  ORoute::post('/background-list',            BackgroundListAction::class,           [AdminFilter::class]);
  ORoute::post('/character-list',             CharacterListAction::class,            [AdminFilter::class]);
  ORoute::post('/delete-asset',               DeleteAssetAction::class,              [AdminFilter::class]);
  ORoute::post('/delete-background',          DeleteBackgroundAction::class,         [AdminFilter::class]);
  ORoute::post('/delete-background-category', DeleteBackgroundCategoryAction::class, [AdminFilter::class]);
  ORoute::post('/delete-character',           DeleteCharacterAction::class,          [AdminFilter::class]);
  ORoute::post('/delete-connection',          DeleteConnectionAction::class,         [AdminFilter::class]);
  ORoute::post('/delete-item',                DeleteItemAction::class,               [AdminFilter::class]);
  ORoute::post('/delete-scenario',            DeleteScenarioAction::class,           [AdminFilter::class]);
  ORoute::post('/delete-scenario-object',     DeleteScenarioObjectAction::class,     [AdminFilter::class]);
  ORoute::post('/delete-world',               DeleteWorldAction::class,              [AdminFilter::class]);
  ORoute::post('/generate-map',               GenerateMapAction::class,              [AdminFilter::class]);
  ORoute::post('/get-scenario',               GetScenarioAction::class,              [AdminFilter::class]);
  ORoute::post('/item-list',                  ItemListAction::class,                 [AdminFilter::class]);
  ORoute::post('/save-asset',                 SaveAssetAction::class,                [AdminFilter::class]);
  ORoute::post('/save-background',            SaveBackgroundAction::class,           [AdminFilter::class]);
  ORoute::post('/save-background-category',   SaveBackgroundCategoryAction::class,   [AdminFilter::class]);
  ORoute::post('/save-character',             SaveCharacterAction::class,            [AdminFilter::class]);
  ORoute::post('/save-connection',            SaveConnectionAction::class,           [AdminFilter::class]);
  ORoute::post('/save-item',                  SaveItemAction::class,                 [AdminFilter::class]);
  ORoute::post('/save-scenario',              SaveScenarioAction::class,             [AdminFilter::class]);
  ORoute::post('/save-scenario-data',         SaveScenarioDataAction::class,         [AdminFilter::class]);
  ORoute::post('/save-scenario-object',       SaveScenarioObjectAction::class,       [AdminFilter::class]);
  ORoute::post('/save-world',                 SaveWorldAction::class,                [AdminFilter::class]);
  ORoute::post('/scenario-list',              ScenarioListAction::class,             [AdminFilter::class]);
  ORoute::post('/scenario-object-list',       ScenarioObjectListAction::class,       [AdminFilter::class]);
  ORoute::post('/select-world-start',         SelectWorldStartAction::class,         [AdminFilter::class]);
  ORoute::post('/tag-list',                   TagListAction::class,                  [AdminFilter::class]);
  ORoute::post('/world-list',                 WorldListAction::class,                [AdminFilter::class]);
});
