{
  "status": "{{status}}",
  "id": {{id}},
  "name": "{{name}}",
  "type": {{type}},
  "activable": {{activable}},
  "pickable": {{pickable}},
  "grabbable": {{grabbable}},
  "breakable": {{breakable}},
  "crossable": {{crossable}},
  "crossable_active": {{crossable_active}},
  "sprite_start_id": {{sprite_start_id}},
  "sprite_start_name": "{{sprite_start_name}}",
  "sprite_start_url": "{{sprite_start_url}}",
  "sprite_active_id": {{sprite_active_id}},
  "sprite_active_name": "{{sprite_active_name}}",
  "sprite_active_url": "{{sprite_active_url}}",
  "drops": {{drops}},
  "quantity": {{quantity}},
  "active_time": {{active_time}}
}